name: Update Semver
on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*.*.*'
jobs:
  update-semver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rickstaa/action-update-semver@add_tag_signing
        with:
          gpg_private_key: "${{ secrets.GPG_PRIVATE_KEY }}"
