name: test rickstaa/action-create-tag
on:
  push:
    branches:
      - main
jobs:
  tag-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: rickstaa/action-create-tag@main 
        with:
          tag: "test tag regular"
          message: "Test tag regular"
      - uses: rickstaa/action-create-tag@main 
        with:
          tag: "test tag force"
          message: "Test tag force"
          force_push_tag: true
      - uses: rickstaa/action-create-tag@main 
        with:
          tag: "test tag no verify"
          message: "Test tag no verify"
          no_verify_tag: true
