name: release
on:
  push:
    branches:
      - master
jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rickstaa/action-get-semver@v1
      - name: Print semver
        id: get_semver
        with:
          bump_level: "minor"
        run: |
          echo "Current version: ${{ steps.get_semver.outputs.current_version  }}"
          echo "Next version: ${{ steps.get_semver.outputs.next_version }}"
