name: release
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Semver
        uses: rickstaa/action-get-semver@v1.0.1
