name: test rickstaa/action-create-tag
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  tag-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Print GitHub context
        run: |
          echo "GitHub context: ${{ toJson(github) }}"

      - name: Print GITHUB_SHA
        run: |
          echo "GITHUB_SHA: ${{ github.sha }}"

      - uses: rickstaa/action-create-tag@main
        with:
          tag: "test tag regular"
          message: "Test tag regular"
          tag_exists_error: false
      - uses: rickstaa/action-create-tag@main
        with:
          tag: "test tag force"
          message: "Test tag force"
          force_push_tag: true
      - uses: rickstaa/action-create-tag@main
        with:
          tag: "test tag no verify"
          message: "Test tag no verify"
          no_verify_tag: true
          tag_exists_error: false
      - uses: rickstaa/action-create-tag@main
        id: tag_create
        with:
          tag: "test tag exists"
          message: "Test tag exists"
          tag_exists_error: false
      # Print result using the env variable.
      - run: |
          echo "Tag already present: ${{ env.TAG_EXISTS }}"

      # Print result using the action output.
      - run: |
          echo "Tag already present: ${{ steps.tag_create.outputs.tag_exists }}"

      - uses: rickstaa/action-create-tag@main
        id: tag_create2
        with:
          tag: "test tag exists not"
          message: "Test tag exists"
          tag_exists_error: false
      # Print result using the env variable.
      - run: |
          echo "Tag already present: ${{ env.TAG_EXISTS }}"

      # Print result using the action output.
      - run: |
          echo "Tag already present: ${{ steps.tag_create2.outputs.tag_exists }}"

      - uses: rickstaa/action-create-tag@add_tag_exists_conditions
        with:
          tag: "test tag exists"
          message: "Test tag exists crash"
