name: test rickstaa/action-create-tag
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  tag-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Print GitHub context
        run: |
          echo "GitHub context: ${{ toJson(github) }}"

      - name: Print GITHUB_SHA
        run: |
          echo "GITHUB_SHA: ${{ github.sha }}"

      - name: Test tag regular
        uses: rickstaa/action-create-tag@main
        with:
          tag: "tag_regular"
          message: "Test tag regular"
          tag_exists_error: false
      - name: Test tag force
        uses: rickstaa/action-create-tag@main
        with:
          tag: "tag_force"
          message: "Test tag force"
          force_push_tag: true
      - name: Test tag no verify
        uses: rickstaa/action-create-tag@main
        with:
          tag: "tag_no_verify"
          message: "Test tag no verify"
          no_verify_tag: true
          tag_exists_error: false

      # - name: Test tag exists
      #   uses: rickstaa/action-create-tag@main
      #   id: tag_create
      #   with:
      #     tag: "tag_exists"
      #     message: "Test tag exists"
      #     tag_exists_error: false
      # # Print result using the ensv variable.
      # - name: Print tag exists result using the env variable.
      #   run: |
      #     echo "Tag already present: ${{ env.TAG_EXISTS }}"
      # # Print result using the action output.
      # - name: Print tag exists result using the action output.
      #   run: |
      #     echo "Tag already present: ${{ steps.tag_create.outputs.tag_exists }}"

      # - name: Test tag exists no error
      #   uses: rickstaa/action-create-tag@main
      #   id: tag_create2
      #   with:
      #     tag: "tag_exists_not"
      #     message: "Test tag exists"
      #     tag_exists_error: false
      # # Print result using the env variable.
      # - name: Print tag exists no error result using the env variable.
      #   run: |
      #     echo "Tag already present: ${{ env.TAG_EXISTS }}"
      # # Print result using the action output.
      # - name: Print tag exists no error result using the action output.
      #   run: |
      #     echo "Tag already present: ${{ steps.tag_create2.outputs.tag_exists }}"

      - name: Test tag GPG signing.
        uses: rickstaa/action-create-tag@add_tag_signing
        with:
          tag: "tag_gpg"
          message: "Test tag GPG signing"
          tag_exists_error: false
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}

      # - name: Test tag exists error
      #   uses: rickstaa/action-create-tag@add_tag_exists_conditions
      #   with:
      #     tag: "tag_exists"
      #     message: "Test tag exists crash"
